# Embadding Layer

## Embedding Layer Toy Example

### Imports

In [2]:
import numpy as np
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten

### Data

In [4]:
reviews = [
  'never comming back',
  'horrible service',
  'rude waitress',
  'cold foot',
  'horrible food',
  'awesome',
  'awesome service',
  'rocks',
  'poor work',
  'could not have done better'
]

# (1 = Negative, 0 = Positive)
labels = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

### Encode Data

In [10]:
vocab_size = 50
encoded_reviews = [one_hot(review, n = vocab_size) for review in reviews]
print('Encoded Reviews:', encoded_reviews)

Encoded Reviews: [[32, 21, 10], [47, 41], [24, 36], [37, 25], [47, 12], [15], [15, 41], [9], [4, 3], [2, 3, 22, 12, 39]]


### Pad Data

In [11]:
maxlen = 4
padded_reviews = pad_sequences(sequences = encoded_reviews, maxlen = maxlen, padding = 'post')
print('Padded Reviews:', padded_reviews)

Padded Reviews: [[32 21 10  0]
 [47 41  0  0]
 [24 36  0  0]
 [37 25  0  0]
 [47 12  0  0]
 [15  0  0  0]
 [15 41  0  0]
 [ 9  0  0  0]
 [ 4  3  0  0]
 [ 3 22 12 39]]


### Build Model

In [15]:
model = Sequential()
model.add(Embedding(input_dim = vocab_size, output_dim = 8, input_length = maxlen))
model.add(Flatten())
model.add(Dense(units = 1, activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['acc'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_1 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


### Train Model

In [16]:
model.fit(padded_reviews, labels, epochs = 100, verbose = False)

### Evaluate Model

In [17]:
loss, acc = model.evaluate(padded_reviews, labels, verbose = False)
print(f'Loss: {loss}, Accuracy: {acc}')

Loss: 0.4816771149635315, Accuracy: 1.0
